<?php
declare(strict_types=1);

/** Stage 2 — test the database connection, import schema.sql, persist config/database.php. */

$current = require CONFIG_PATH . '/database.php';

// If the currently configured DB already has the app schema, this is an
// existing site that just lost its lock (e.g. an update overwrote storage/).
$currentHasSchema = false;
try {
    $currentHasSchema = Database::databaseHasSchema(Database::testConnection($current['host'], (int) $current['port'], $current['database'], $current['username'], $current['password'] ?? ''));
} catch (Throwable $e) {
    $currentHasSchema = false;
}

if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    Csrf::requireValid();

    $host = trim($_POST['db_host'] ?? '');
    $port = (int) ($_POST['db_port'] ?? 3306);
    $name = trim($_POST['db_name'] ?? '');
    $user = trim($_POST['db_username'] ?? '');
    $pass = (string) ($_POST['db_password'] ?? '');
    keepOld(['db_host' => $host, 'db_port' => (string) $port, 'db_name' => $name, 'db_username' => $user]);

    if ($host === '' || $name === '' || $user === '') {
        $errors[] = 'Host, database name, and username are required.';
    } else {
        try {
            $pdo = Database::testConnection($host, $port, $name, $user, $pass);

            // Existing installation? Reconnect instead of re-importing so the
            // database is never touched — updates must never lose data.
            $isExisting = Database::databaseHasSchema($pdo);
            if ($isExisting) {
                $_SESSION['install']['existing_install'] = true;
            } else {
                Database::importSqlFile($pdo, INSTALLER_PATH . '/schema.sql');
            }

            $configContents = "<?php\n" .
                "declare(strict_types=1);\n\n" .
                "/**\n * Generated by the installer on " . date('Y-m-d H:i:s') . ".\n" .
                " * Regenerate by deleting storage/installed.lock and re-running /install.\n */\n" .
                "return " . var_export([
                    'driver' => 'mysql',
                    'host' => $host,
                    'port' => $port,
                    'database' => $name,
                    'username' => $user,
                    'password' => $pass,
                    'charset' => 'utf8mb4',
                ], true) . ";\n";
            file_put_contents(CONFIG_PATH . '/database.php', $configContents);

            clearOld();
            // Existing installs jump straight to Finish (step 4): no new admin,
            // no re-branding, just reconnect + restore the lock.
            $_SESSION['install']['max_step'] = max($_SESSION['install']['max_step'], $isExisting ? 4 : 3);
            redirect('/install?step=' . ($isExisting ? 4 : 3));
        } catch (Throwable $e) {
            $errors[] = 'Could not connect or import the schema: ' . $e->getMessage();
        }
    }
}
?>
<h2>Connect your database</h2>
<p class="sub">We'll test the connection and install all required tables.</p>

<?php if ($currentHasSchema): ?>
  <div class="alert success">
    ✅ <strong>Existing installation detected</strong> in this database. Reconnecting will <strong>NOT</strong> delete your data —
    the app will skip the schema import, restore the connection, and take you straight back online.
  </div>
<?php endif; ?>

<?php foreach ($errors as $error): ?>
  <div class="alert error"><?= e($error) ?></div>
<?php endforeach; ?>

<form method="post">
  <?= Csrf::field() ?>
  <div class="row">
    <div>
      <label for="db_host">Database Host</label>
      <input type="text" id="db_host" name="db_host" value="<?= old('db_host', $current['host']) ?>" required>
    </div>
    <div>
      <label for="db_port">Port</label>
      <input type="number" id="db_port" name="db_port" value="<?= old('db_port', (string) $current['port']) ?>" required>
    </div>
  </div>
  <label for="db_name">Database Name</label>
  <input type="text" id="db_name" name="db_name" value="<?= old('db_name', $current['database']) ?>" required>
  <label for="db_username">Database Username</label>
  <input type="text" id="db_username" name="db_username" value="<?= old('db_username', $current['username']) ?>" required>
  <label for="db_password">Database Password</label>
  <input type="password" id="db_password" name="db_password" placeholder="Leave blank if none (local dev)">
  <button class="btn" type="submit">Test Connection &amp; Install Schema</button>
</form>
