<?php
declare(strict_types=1);

/** Stage 4 — generate a fresh fingerprint salt, lock the installer, show a security checklist. */

if (!APP_IS_INSTALLED && empty($_SESSION['install']['finished'])) {
    $security = require CONFIG_PATH . '/security.php';
    $security['fingerprint_salt'] = bin2hex(random_bytes(32));

    $contents = "<?php\n" .
        "declare(strict_types=1);\n\n" .
        "/**\n * Brute-force thresholds + anonymous fingerprint salt.\n" .
        " * fingerprint_salt was regenerated by the installer on " . date('Y-m-d H:i:s') . ".\n */\n" .
        "return " . var_export($security, true) . ";\n";
    file_put_contents(CONFIG_PATH . '/security.php', $contents);

    file_put_contents(INSTALL_LOCK_FILE, json_encode(['installed_at' => date('c')]));
    $_SESSION['install']['finished'] = true;
}
?>
<h2>You're all set 🎉</h2>
<p class="sub">Church Media Management System has been installed successfully.</p>

<?php if (!empty($_SESSION['install']['existing_install'])): ?>
  <div class="alert success">Reconnected to your existing database — nothing was deleted and your data is intact. The site is live again.</div>
<?php else: ?>
  <div class="alert success">Database connected, schema installed, and your admin account is ready.</div>
<?php endif; ?>

<ul class="check-list">
  <li><span>Delete/rename the <code>installer/</code> folder or block it at the web server</span><span class="badge fail">TO DO</span></li>
  <li><span>Set <code>app_env</code> to <code>production</code> once live</span><span class="badge fail">TO DO</span></li>
  <li><span>Drop a static <code>ffmpeg.exe</code> into <code>bin/ffmpeg/</code> for reel video processing</span><span class="badge fail">TO DO</span></li>
  <li><span>Review Admin → Security for IP/country rules</span><span class="badge fail">TO DO</span></li>
</ul>

<a class="btn" href="/admin/login">Go to Admin Login</a>
<a class="btn secondary" href="/" style="margin-top:10px;">Visit the Website</a>
