<?php
declare(strict_types=1);

/** Singleton PDO wrapper. Reads config/database.php (regenerated by the installer). */
class Database
{
    private static ?Database $instance = null;
    private PDO $connection;

    private function __construct()
    {
        $config = require CONFIG_PATH . '/database.php';
        $dsn = sprintf(
            '%s:host=%s;port=%d;dbname=%s;charset=%s',
            $config['driver'],
            $config['host'],
            $config['port'],
            $config['database'],
            $config['charset']
        );
        $this->connection = new PDO($dsn, $config['username'], $config['password'], [
            PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION,
            PDO::ATTR_DEFAULT_FETCH_MODE => PDO::FETCH_ASSOC,
            // Use client-side emulated prepares: avoids MySQL/MariaDB error 1615
            // ("Prepared statement needs to be re-prepared") on shared hosts where
            // the server-side statement cache is small and evicts statements
            // between prepare() and execute(). PDO quotes values itself, so this
            // is still injection-safe and is PDO's default mode.
            PDO::ATTR_EMULATE_PREPARES => true,
            PDO::MYSQL_ATTR_USE_BUFFERED_QUERY => true,
        ]);
    }

    public static function getInstance(): self
    {
        if (self::$instance === null) {
            self::$instance = new self();
        }
        return self::$instance;
    }

    /**
     * True only when config/database.php exists with credentials that can actually
     * connect. Used at boot to detect a "new environment": a lock file copied from
     * another machine (or rotated credentials) must not make the app believe it is
     * installed and then crash with a raw PDOException on the first page load.
     */
    public static function isReachable(): bool
    {
        $configFile = CONFIG_PATH . '/database.php';
        if (!is_file($configFile)) {
            return false;
        }
        try {
            $config = require $configFile;
            if (empty($config['host']) || empty($config['database']) || empty($config['username'])) {
                return false;
            }
            $dsn = sprintf(
                '%s:host=%s;port=%d;dbname=%s;charset=%s',
                $config['driver'] ?? 'mysql',
                $config['host'],
                $config['port'] ?? 3306,
                $config['database'],
                $config['charset'] ?? 'utf8mb4'
            );
            $pdo = new PDO($dsn, $config['username'], $config['password'] ?? '', [
                PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION,
                PDO::ATTR_TIMEOUT => 3,
            ]);
            $pdo->query('SELECT 1');
            return true;
        } catch (Throwable $e) {
            return false;
        }
    }

    /**
     * True when an arbitrary PDO points at a database that already contains the
     * app's signature tables (i.e. a completed install). Used to tell "fresh
     * install" from "reconnect to an existing site" so updates never lose data.
     */
    public static function databaseHasSchema(PDO $pdo): bool
    {
        try {
            foreach (['settings', 'users', 'media_posts', 'org_units', 'forms'] as $table) {
                $stmt = $pdo->prepare('SELECT COUNT(*) FROM information_schema.TABLES WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = ?');
                $stmt->execute([$table]);
                if ((int) $stmt->fetchColumn() === 0) {
                    return false;
                }
            }
            // Check that at least one admin/user exists to consider it a fully initialized existing install
            $stmt = $pdo->query('SELECT COUNT(*) FROM users');
            if ((int) $stmt->fetchColumn() === 0) {
                return false;
            }
            return true;
        } catch (Throwable $e) {
            return false;
        }
    }

    /** True when the configured database is reachable AND already has the app schema. */
    public static function hasAppSchema(): bool
    {
        if (!self::isReachable()) {
            return false;
        }
        try {
            return self::databaseHasSchema(self::getInstance()->getConnection());
        } catch (Throwable $e) {
            return false;
        }
    }

    public function getConnection(): PDO
    {
        return $this->connection;
    }

    /**
     * Runs idempotent in-place migrations for already-installed databases
     * (the installer only applies schema.sql once, so later feature columns
     * must be added here). Each migration runs at most once and the result is
     * stamped to storage/migrations.json. Failures are logged, never fatal.
     */
    public static function migrate(): void
    {
        try {
            $pdo = self::getInstance()->getConnection();

            // Self-healing: Apply idempotent schema.sql to automatically create any
            // missing core tables or default seed pages (e.g. privacy-policy, about).
            try {
                self::importSqlFile($pdo, INSTALLER_PATH . '/schema.sql');
            } catch (Throwable $e) {
                error_log('Schema import auto-heal notice: ' . $e->getMessage());
            }

            $stampFile = STORAGE_PATH . '/migrations.json';
            $done = [];
            if (is_file($stampFile)) {
                $decoded = json_decode((string) file_get_contents($stampFile), true);
                $done = is_array($decoded) ? $decoded : [];
            }
            foreach (self::migrations() as $name => $fn) {
                try {
                    $fn($pdo);
                } catch (Throwable $e) {
                    error_log('Migration ' . $name . ' auto-heal notice: ' . $e->getMessage());
                }
                if (!in_array($name, $done, true)) {
                    $done[] = $name;
                }
            }
            @file_put_contents($stampFile, json_encode($done));
        } catch (Throwable $e) {
            error_log('Database::migrate skipped: ' . $e->getMessage());
        }
    }

    private static function migrations(): array
    {
        return [
            '2026_01_media_source' => function (PDO $pdo): void {
                self::addColumnIfMissing($pdo, 'media_post_items', 'source', "ENUM('upload','youtube') NOT NULL DEFAULT 'upload'", 'type');
            },
            '2026_01_media_saves' => function (PDO $pdo): void {
                self::addColumnIfMissing($pdo, 'media_posts', 'saves_count', 'INT NOT NULL DEFAULT 0', 'views_count');
            },
            '2026_01_media_engagement' => function (PDO $pdo): void {
                $pdo->exec("CREATE TABLE IF NOT EXISTS `post_saves` (
                    `id` INT AUTO_INCREMENT PRIMARY KEY,
                    `media_post_id` INT NOT NULL,
                    `fingerprint_hash` VARCHAR(64) NOT NULL,
                    `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                    UNIQUE KEY `uniq_save_post_fingerprint` (`media_post_id`, `fingerprint_hash`),
                    FOREIGN KEY (`media_post_id`) REFERENCES `media_posts`(`id`) ON DELETE CASCADE
                ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4");
                $pdo->exec("CREATE TABLE IF NOT EXISTS `post_comments` (
                    `id` INT AUTO_INCREMENT PRIMARY KEY,
                    `media_post_id` INT NOT NULL,
                    `name` VARCHAR(100) NULL,
                    `message` TEXT NOT NULL,
                    `fingerprint_hash` VARCHAR(64) NULL,
                    `is_published` TINYINT(1) NOT NULL DEFAULT 1,
                    `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                    FOREIGN KEY (`media_post_id`) REFERENCES `media_posts`(`id`) ON DELETE CASCADE,
                    INDEX `idx_comment_post` (`media_post_id`, `created_at`)
                ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4");
            },
            '2026_08_media_converted_at' => function (PDO $pdo): void {
                // Set when an uploaded video finishes its 9:16 crop. NULL means it
                // still plays the original (conversion pending or ffmpeg absent).
                self::addColumnIfMissing($pdo, 'media_post_items', 'converted_at', 'DATETIME NULL', 'processing_status');
            },
            '2026_08_forms' => function (PDO $pdo): void {
                $pdo->exec("CREATE TABLE IF NOT EXISTS `forms` (
                    `id` INT AUTO_INCREMENT PRIMARY KEY,
                    `title` VARCHAR(200) NOT NULL,
                    `slug` VARCHAR(220) NOT NULL UNIQUE,
                    `description` TEXT NULL,
                    `submit_label` VARCHAR(100) NOT NULL DEFAULT 'Submit',
                    `end_at` DATETIME NULL COMMENT 'Optional validity end date; NULL = open-ended',
                    `is_active` TINYINT(1) NOT NULL DEFAULT 1,
                    `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                    `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
                    INDEX `idx_active_end` (`is_active`, `end_at`)
                ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4");
                $pdo->exec("CREATE TABLE IF NOT EXISTS `form_fields` (
                    `id` INT AUTO_INCREMENT PRIMARY KEY,
                    `form_id` INT NOT NULL,
                    `label` VARCHAR(255) NOT NULL,
                    `field_type` ENUM('text','textarea','email','phone','number','date','url','select','radio','checkbox') NOT NULL DEFAULT 'text',
                    `placeholder` VARCHAR(255) NULL,
                    `options` TEXT NULL COMMENT 'One option per line (select/radio/checkbox)',
                    `required` TINYINT(1) NOT NULL DEFAULT 0,
                    `sort_order` INT NOT NULL DEFAULT 0,
                    `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                    FOREIGN KEY (`form_id`) REFERENCES `forms`(`id`) ON DELETE CASCADE,
                    INDEX `idx_field_form_order` (`form_id`, `sort_order`)
                ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4");
                $pdo->exec("CREATE TABLE IF NOT EXISTS `form_submissions` (
                    `id` INT AUTO_INCREMENT PRIMARY KEY,
                    `form_id` INT NOT NULL,
                    `data` LONGTEXT NOT NULL COMMENT 'JSON map of field id -> value',
                    `ip_address` VARCHAR(45) NULL,
                    `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                    FOREIGN KEY (`form_id`) REFERENCES `forms`(`id`) ON DELETE CASCADE,
                    INDEX `idx_submission_form_time` (`form_id`, `created_at`)
                ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4");
            },
            '2026_08_forms_image_field' => function (PDO $pdo): void {
                // Widens form_fields.field_type to accept the new 'image' upload type.
                $pdo->exec("ALTER TABLE `form_fields` MODIFY COLUMN `field_type` ENUM('text','textarea','email','phone','number','date','url','select','radio','checkbox','image') NOT NULL DEFAULT 'text'");
            },
            '2026_08_pages' => function (PDO $pdo): void {
                // Homepage hero: editable eyebrow text, background image, video/youtube background, and CTA labels/links.
                self::addColumnIfMissing($pdo, 'settings', 'hero_eyebrow', "VARCHAR(120) NULL", 'hero_scripture');
                self::addColumnIfMissing($pdo, 'settings', 'hero_image_path', "VARCHAR(255) NULL", 'hero_eyebrow');
                self::addColumnIfMissing($pdo, 'settings', 'hero_type', "VARCHAR(20) NOT NULL DEFAULT 'gradient'", 'hero_image_path');
                self::addColumnIfMissing($pdo, 'settings', 'hero_video_path', "VARCHAR(255) NULL", 'hero_type');
                self::addColumnIfMissing($pdo, 'settings', 'hero_youtube_url', "VARCHAR(500) NULL", 'hero_video_path');
                self::addColumnIfMissing($pdo, 'settings', 'hero_cta_primary_label', "VARCHAR(60) NULL", 'hero_youtube_url');
                self::addColumnIfMissing($pdo, 'settings', 'hero_cta_primary_url', "VARCHAR(500) NULL", 'hero_cta_primary_label');
                self::addColumnIfMissing($pdo, 'settings', 'hero_cta_secondary_label', "VARCHAR(60) NULL", 'hero_cta_primary_url');
                self::addColumnIfMissing($pdo, 'settings', 'hero_cta_secondary_url', "VARCHAR(500) NULL", 'hero_cta_secondary_label');

                // CMS pages table (JSON section-based content rendered into a template).
                $pdo->exec("CREATE TABLE IF NOT EXISTS `pages` (
                    `id` INT AUTO_INCREMENT PRIMARY KEY,
                    `parent_id` INT NULL DEFAULT NULL,
                    `title` VARCHAR(200) NOT NULL,
                    `slug` VARCHAR(220) NOT NULL UNIQUE,
                    `eyebrow` VARCHAR(120) NULL,
                    `content` LONGTEXT NULL COMMENT 'JSON array of content sections',
                    `meta_description` VARCHAR(255) NULL,
                    `in_nav` TINYINT(1) NOT NULL DEFAULT 0,
                    `nav_label` VARCHAR(60) NULL,
                    `is_published` TINYINT(1) NOT NULL DEFAULT 1,
                    `sort_order` INT NOT NULL DEFAULT 0,
                    `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                    `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
                    INDEX `idx_page_nav` (`is_published`, `in_nav`, `sort_order`)
                ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4");

                // Seed the About page so the existing /about link has CMS content.
                $check = $pdo->prepare('SELECT COUNT(*) FROM pages WHERE slug = ?');
                $check->execute(['about']);
                if (!(int) $check->fetchColumn()) {
                    $content = json_encode([
                        ['type' => 'text', 'heading' => 'Welcome to Grace & Life Church', 'body' => 'We are a family of believers on a journey together — growing in faith, building community, and serving our city with the love of Christ.', 'align' => 'center'],
                        ['type' => 'columns', 'heading' => 'Why We Exist', 'columns' => [
                            ['heading' => 'Our Mission', 'body' => 'To lead people into a growing relationship with God, build authentic community, and serve our city with the love of Christ.'],
                            ['heading' => 'Our Vision', 'body' => 'A church without walls — reaching every generation, in the room and online, with hope that lasts.'],
                            ['heading' => 'Our Values', 'body' => 'Grace first. People over programs. Faith in action. Generosity, humility, and love in everything we do.'],
                        ]],
                        ['type' => 'quote', 'quote' => 'Wherever you are on your journey, you are welcome here — exactly as you are.', 'source' => 'Grace & Life Church'],
                        ['type' => 'cta', 'title' => 'Come worship with us this weekend', 'subtitle' => 'Every Sunday — in the room and online.', 'label' => 'Plan a Visit', 'url' => '/contact'],
                    ], JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE);
                    $pdo->prepare('INSERT INTO pages (title, slug, eyebrow, content, meta_description, in_nav, nav_label, sort_order) VALUES (?, ?, ?, ?, ?, 1, ?, 10)')
                        ->execute(['About Us', 'about', 'Our Story', $content, 'Learn about our story, mission, vision, and values.', 'About']);
                }
            },
            '2026_08_service_times_seed' => function (PDO $pdo): void {
                // Store the default service schedule in the settings row so the
                // DB is the single source of truth for every display spot (home,
                // footer, contact, live) and the mobile app API. Previously the
                // public site fell back to config/site.php when this was NULL,
                // which made the schedule look hardcoded.
                $count = (int) $pdo->query('SELECT COUNT(*) FROM settings WHERE service_times IS NULL OR service_times = ""')->fetchColumn();
                if ($count > 0) {
                    $siteDefaults = require CONFIG_PATH . '/site.php';
                    $seed = $siteDefaults['service_times'] ?? '[]';
                    $pdo->prepare('UPDATE settings SET service_times = ? WHERE service_times IS NULL OR service_times = ""')->execute([$seed]);
                }
            },
            '2026_08_bible_settings' => function (PDO $pdo): void {
                // Bible page source + API key, chosen by the admin at /admin/settings.
                // 'keyless' uses public-domain providers (no key); 'api_bible' uses
                // scripture.api.bible for NIV/NLT/NKJV with the stored access token.
                self::addColumnIfMissing($pdo, 'settings', 'bible_source', "VARCHAR(20) NOT NULL DEFAULT 'keyless'", 'meta_description');
                self::addColumnIfMissing($pdo, 'settings', 'bible_api_key', 'VARCHAR(255) NULL', 'bible_source');
            },
            '2026_08_super_admin' => function (PDO $pdo): void {
                // Explicit super-admin flag so the owner account can't be edited,
                // suspended, or deleted by other admins. Existing installs: the
                // first account (lowest id) becomes the super admin, matching the
                // previous implicit protection.
                self::addColumnIfMissing($pdo, 'users', 'is_super_admin', "TINYINT(1) NOT NULL DEFAULT 0", 'role');
                $count = (int) $pdo->query('SELECT COUNT(*) FROM users WHERE is_super_admin = 1')->fetchColumn();
                if ($count === 0) {
                    $pdo->exec("UPDATE users SET is_super_admin = 1 WHERE id = (SELECT id FROM (SELECT MIN(id) AS id FROM users) t)");
                }
            },
            '2026_08_org_units' => function (PDO $pdo): void {
                // Province → Zone → Area → Parish hierarchy (RCCG-style). One
                // self-referencing table; posts are tagged to a parish and roll
                // up to area/zone/province. A default 'Headquarters' is seeded
                // so existing users/posts are never orphaned.
                $pdo->exec("CREATE TABLE IF NOT EXISTS `org_units` (
                    `id` INT AUTO_INCREMENT PRIMARY KEY,
                    `parent_id` INT NULL,
                    `type` ENUM('province','zone','area','parish') NOT NULL,
                    `name` VARCHAR(150) NOT NULL,
                    `slug` VARCHAR(160) NULL UNIQUE,
                    `sort_order` INT NOT NULL DEFAULT 0,
                    `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                    FOREIGN KEY (`parent_id`) REFERENCES `org_units`(`id`) ON DELETE CASCADE
                ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4");
                self::addColumnIfMissing($pdo, 'users', 'org_unit_id', 'INT NULL', 'role');
                self::addColumnIfMissing($pdo, 'media_posts', 'org_unit_id', 'INT NULL', 'user_id');
                self::addForeignKeyIfMissing($pdo, 'users', 'fk_users_org_unit', 'org_unit_id', 'org_units', 'id', 'SET NULL');
                self::addForeignKeyIfMissing($pdo, 'media_posts', 'fk_media_posts_org_unit', 'org_unit_id', 'org_units', 'id', 'SET NULL');
                if ((int) $pdo->query('SELECT COUNT(*) FROM org_units')->fetchColumn() === 0) {
                    $pdo->prepare("INSERT INTO org_units (type, name, slug) VALUES ('province', ?, ?)")->execute(['Headquarters', 'headquarters']);
                    $provinceId = (int) $pdo->lastInsertId();
                    $pdo->prepare("INSERT INTO org_units (parent_id, type, name, slug) VALUES (?, 'parish', ?, ?)")->execute([$provinceId, 'Headquarters Parish', 'headquarters-parish']);
                    $parishId = (int) $pdo->lastInsertId();
                    $pdo->exec("UPDATE users SET org_unit_id = {$parishId} WHERE org_unit_id IS NULL");
                    $pdo->exec("UPDATE media_posts SET org_unit_id = {$parishId} WHERE org_unit_id IS NULL");
                }
            },
            '2026_08_unit_isolation' => function (PDO $pdo): void {
                // Per-church admin isolation: every content module carries the
                // owning unit so a church's admin/editor/media team only sees
                // their own church's data. Unassigned rows are only visible to
                // the super admin (or can be reassigned).
                foreach (['events', 'sermons', 'team_members', 'newsletter_subscribers', 'forms', 'prayer_requests'] as $table) {
                    self::addColumnIfMissing($pdo, $table, 'org_unit_id', 'INT NULL', null);
                    self::addForeignKeyIfMissing($pdo, $table, 'fk_' . $table . '_org_unit', 'org_unit_id', 'org_units', 'id', 'SET NULL');
                }
            },
            '2026_08_smtp' => function (PDO $pdo): void {
                // SMTP mail settings (super admin configures in Settings -> Email).
                $smtpColumns = [
                    'smtp_host' => 'VARCHAR(255) NULL',
                    'smtp_port' => 'INT NULL',
                    'smtp_secure' => "VARCHAR(10) NULL DEFAULT 'tls'",
                    'smtp_username' => 'VARCHAR(255) NULL',
                    'smtp_password' => 'VARCHAR(255) NULL',
                    'smtp_from' => 'VARCHAR(255) NULL',
                ];
                foreach ($smtpColumns as $col => $def) {
                    self::addColumnIfMissing($pdo, 'settings', $col, $def, 'bible_api_key');
                }
            },
            '2026_08_notifications' => function (PDO $pdo): void {
                // Provincial announcements: a province admin (or super admin)
                // broadcasts to all churches, one church, or selected churches.
                // Recipients surface on the admin dashboard and get an email.
                $pdo->exec("CREATE TABLE IF NOT EXISTS `notifications` (
                    `id` INT AUTO_INCREMENT PRIMARY KEY,
                    `sender_id` INT NULL,
                    `title` VARCHAR(255) NOT NULL,
                    `body` TEXT NOT NULL,
                    `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                    FOREIGN KEY (`sender_id`) REFERENCES `users`(`id`) ON DELETE SET NULL
                ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4");
                $pdo->exec("CREATE TABLE IF NOT EXISTS `notification_recipients` (
                    `id` INT AUTO_INCREMENT PRIMARY KEY,
                    `notification_id` INT NOT NULL,
                    `org_unit_id` INT NOT NULL,
                    `read_at` DATETIME NULL,
                    `delivered_at` DATETIME NULL,
                    FOREIGN KEY (`notification_id`) REFERENCES `notifications`(`id`) ON DELETE CASCADE,
                    FOREIGN KEY (`org_unit_id`) REFERENCES `org_units`(`id`) ON DELETE CASCADE,
                    UNIQUE KEY `uq_notif_recipient` (`notification_id`, `org_unit_id`)
                ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4");
            },
            '2026_08_comments_upgrade' => function (PDO $pdo): void {
                // Instagram-style comments: threaded replies, image attachments
                // (auto-compressed to the smallest webp), and comment likes.
                self::addColumnIfMissing($pdo, 'post_comments', 'parent_id', 'INT NULL', 'media_post_id');
                self::addColumnIfMissing($pdo, 'post_comments', 'image_path', 'VARCHAR(255) NULL', 'message');
                self::addColumnIfMissing($pdo, 'post_comments', 'likes_count', 'INT NOT NULL DEFAULT 0', 'image_path');
                self::addForeignKeyIfMissing($pdo, 'post_comments', 'fk_post_comments_parent', 'parent_id', 'post_comments', 'id', 'CASCADE');
                $pdo->exec("CREATE TABLE IF NOT EXISTS `post_comment_likes` (
                    `id` INT AUTO_INCREMENT PRIMARY KEY,
                    `comment_id` INT NOT NULL,
                    `fingerprint_hash` VARCHAR(64) NULL,
                    `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                    UNIQUE KEY `uniq_comment_like` (`comment_id`, `fingerprint_hash`),
                    FOREIGN KEY (`comment_id`) REFERENCES `post_comments`(`id`) ON DELETE CASCADE
                ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4");
            },
            '2026_08_device_tokens' => function (PDO $pdo): void {
                // Push device tokens registered by the mobile app (for FCM).
                // Tokens are anonymous; an optional org_unit_id lets a device
                // receive per-church pushes without a login.
                $pdo->exec("CREATE TABLE IF NOT EXISTS `device_tokens` (
                    `id` INT AUTO_INCREMENT PRIMARY KEY,
                    `token` VARCHAR(512) NOT NULL,
                    `platform` VARCHAR(30) NULL,
                    `org_unit_id` INT NULL,
                    `user_agent` VARCHAR(255) NULL,
                    `last_seen_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
                    `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                    UNIQUE KEY `uniq_device_token` (`token`(255)),
                    FOREIGN KEY (`org_unit_id`) REFERENCES `org_units`(`id`) ON DELETE SET NULL
                ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4");
            },
            '2026_08_privacy_policy' => function (PDO $pdo): void {
                // Seed/update a comprehensive privacy policy page (served at /page/privacy-policy).
                // Content uses {{site_title}} / {{contact_email}} / {{contact_phone}}
                // / {{address}} / {{site_url}} tokens, resolved from admin settings at render time.
                $content = json_encode([
                    ['type' => 'text', 'heading' => 'Privacy Policy', 'body' => 'Effective date: {{effective_date}}' . "\n\n" . '{{site_title}} ("we", "us", or "our") is committed to protecting your privacy and upholding the trust you place in our ministry. This Privacy Policy governs our website, our mobile application (available on Google Play Store), online giving and donation platforms, advertisement placement services, and all related services operated by {{site_title}}.', 'align' => 'center'],
                    ['type' => 'text', 'heading' => '1. Introduction & Scope', 'body' => "This policy outlines how {{site_title}} collects, uses, protects, and discloses personal information obtained through our digital platforms, including:\n- Our official website ({{site_url}})\n- Our Android mobile application on the Google Play Store\n- Account registration, member portals, and Church Unit administration\n- Online giving, tithes, offerings, and event registrations\n- Advertising placement orders and publisher ad management\n- Contact forms, prayer requests, and interactive media features\n\nBy accessing or using our website, mobile app, or services, you agree to the collection and use of information in accordance with this policy.", 'align' => 'left'],
                    ['type' => 'text', 'heading' => '2. Information We Collect', 'body' => "We collect several types of information from and about users of our services:\n\na) Account & Member Information:\nWhen you register an account, request Church Unit membership, or update your profile, we collect your full name, primary email address, phone number, alternate email address, assigned parish/unit, security unblock PIN, and account password (stored securely as a cryptographic hash).\n\nb) Financial Donations & Giving Details:\nWhen you make voluntary donations, tithes, offerings, or event payments through our platform, transaction details (such as donation amounts, payment references, date, and time) are processed through secure payment gateways. We do not store raw credit card numbers or bank credentials on our servers.\n\nc) Advertising Placement & Publisher Data:\nWhen you place an order to advertise on our website and mobile app, we collect your business/publisher contact details, selected ad package, target destination link, uploaded media files (9:16 vertical images or videos), and payment proof/checkout receipt.\n\nd) User Content & Interactive Submissions:\nWe collect information you voluntarily post or submit, including prayer requests, newcomer forms, comments, saved media items, and direct messages sent through our contact channels.\n\ne) Mobile Application & Technical Device Data:\nWhen using our Android app on Google Play or visiting our website, we automatically collect technical details such as your device model, operating system version, unique device tokens for Firebase Cloud Messaging (FCM) push notifications, IP address, approximate geographical location, browser type, and app feature interactions.", 'align' => 'left'],
                    ['type' => 'text', 'heading' => '3. How We Use Your Information', 'body' => "We process your personal information for the following purposes:\n- Service Delivery: To operate our website, mobile app, live video feeds, sermon archives, and digital Bible reading features.\n- Account & Access Management: To verify account credentials, manage member permissions, and process password resets or Security PIN account unblocks.\n- Financial Processing: To process tithes, offerings, event registrations, and ad placement payments accurately and generate confirmation receipts.\n- Advertisements & Media Management: To format, review, approve, and render 9:16 vertical display ads on our feed and mobile app, and send performance analytics to ad publishers.\n- Communication & Notifications: To send requested newsletters, church updates, event reminders, and real-time push notifications via Firebase Cloud Messaging.\n- Ministry & Community Care: To respond to prayer requests, contact form submissions, and newcomer follow-up requests.\n- Platform Security & Optimization: To prevent fraudulent activity, mitigate security threats, analyze aggregate usage metrics, and improve user experience.", 'align' => 'left'],
                    ['type' => 'text', 'heading' => '4. Payment Processing & Gateways', 'body' => "All financial transactions (including donations and ad purchases) are processed through accredited, encrypted payment gateways (including Payhub and direct bank transfer verification).\n\n- Online Payment Gateways: Payment processors operate using secure SSL/TLS encryption and HMAC-SHA256 signature verification. Payment processors handle card details directly in accordance with PCI-DSS standards.\n- Manual Bank Transfers: When you upload proof of bank transfer receipts, the file is securely stored on our server and accessible exclusively by authorized church administrators for payment verification.", 'align' => 'left'],
                    ['type' => 'text', 'heading' => '5. Mobile App Permissions & Notifications', 'body' => "Our mobile application on the Google Play Store offers enhanced features designed to enrich your experience:\n- Push Notifications: With your consent, we use Firebase Cloud Messaging (FCM) to send real-time alerts for live broadcasts, daily devotionals, and church announcements. You can disable push notifications at any time in your device settings.\n- Storage & Camera Access: If you choose to upload media for ad placements, profile pictures, or prayer requests, the app may request permission to access your device storage or camera. These permissions are strictly opt-in and can be revoked whenever desired.", 'align' => 'left'],
                    ['type' => 'text', 'heading' => '6. Cookies, Analytics & Display Advertising', 'body' => "We use essential cookies and local browser storage to keep you securely signed in, protect against Cross-Site Request Forgery (CSRF), and save your playback preferences.\n\nDisplay Advertisements rendered on our feed and mobile app are pre-screened and approved by our administrators. Ad engagement metrics (views and clicks) are recorded anonymously to provide statistical reporting in the Publisher Ad Manager portal.", 'align' => 'left'],
                    ['type' => 'text', 'heading' => '7. Data Sharing & Third-Party Disclosure', 'body' => "We respect your trust and do NOT sell, rent, or trade your personal information to third-party marketers.\n\nInformation is disclosed only under these strict conditions:\n- Trusted Service Providers: Third-party infrastructure providers who assist in operating our platform (hosting providers, SMTP email servers, push notification services, and payment gateways) bound by confidentiality obligations.\n- Church Unit Leaders: Relevant pastoral and administrative leaders within {{site_title}} for newcomer care, prayer requests, or unit administration.\n- Legal & Safeguarding Requirements: When required by law, subpoena, court order, or to protect the safety and rights of our community members.", 'align' => 'left'],
                    ['type' => 'text', 'heading' => '8. Data Security & Cryptographic Protection', 'body' => "We implement industry-standard technical and organizational security measures to protect your data:\n- Cryptographic Hashing: User account passwords and Security Unblock PINs are hashed using Argon2id cryptographic algorithms.\n- Encryption in Transit: All data exchanged between your browser or mobile app and our servers is encrypted using Transport Layer Security (TLS/HTTPS).\n- Access Controls: Administrative access to sensitive donor records, user accounts, and ad transactions is restricted to authorized roles.", 'align' => 'left'],
                    ['type' => 'text', 'heading' => '9. Data Retention & Account Rights', 'body' => "We retain your personal data for as long as your account remains active or as needed to fulfill ministry services, maintain financial record compliance, or satisfy legal requirements.\n\nYour Rights:\nDepending on applicable law, you have the right to:\n- Access and inspect the personal data we hold about you.\n- Correct or update inaccurate or incomplete information.\n- Request deletion of your account and associated personal data.\n- Withdraw consent for push notifications or marketing communications.\n\nTo exercise any of these rights, please submit a request through our contact form or contact our administration directly.", 'align' => 'left'],
                    ['type' => 'text', 'heading' => '10. Children\'s Privacy', 'body' => "Our digital services are designed for general audiences and ministry engagement. We do not knowingly collect personal information from children under 13 without verified parental or guardian consent. If you believe a child has submitted personal data without consent, please contact us immediately for prompt deletion.", 'align' => 'left'],
                    ['type' => 'text', 'heading' => '11. Policy Changes & Updates', 'body' => "We may update this Privacy Policy periodically to reflect technological advancements, service enhancements, or legal modifications. Any revisions will be published on this page with an updated effective date. We encourage you to review this page regularly.", 'align' => 'left'],
                    ['type' => 'text', 'heading' => '12. Contact Us', 'body' => "If you have any questions, concerns, or privacy requests regarding this Privacy Policy or our data practices, please contact us:\n\n{{site_title}}\n{{address}}\nWebsite: {{site_url}}\nEmail: {{contact_email}}\nPhone: {{contact_phone}}", 'align' => 'left'],
                ], JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE);

                $check = $pdo->prepare('SELECT id FROM pages WHERE slug = ? LIMIT 1');
                $check->execute(['privacy-policy']);
                $existingId = $check->fetchColumn();

                if ($existingId) {
                    $pdo->prepare('UPDATE pages SET title = ?, eyebrow = ?, content = ?, meta_description = ?, in_nav = 0, is_published = 1 WHERE id = ?')
                        ->execute([
                            'Privacy Policy',
                            'Legal',
                            $content,
                            'How {{site_title}} collects, uses, and protects your personal information.',
                            $existingId,
                        ]);
                } else {
                    $pdo->prepare('INSERT INTO pages (title, slug, eyebrow, content, meta_description, in_nav, nav_label, is_published, sort_order) VALUES (?, ?, ?, ?, ?, 0, ?, 90)')
                        ->execute([
                            'Privacy Policy',
                            'privacy-policy',
                            'Legal',
                            $content,
                            'How {{site_title}} collects, uses, and protects your personal information.',
                            'Privacy Policy',
                        ]);
                }
                $pdo->exec("UPDATE pages SET in_nav = 0 WHERE slug = 'privacy-policy'");
            },
            '2026_08_donations_and_giving' => function (PDO $pdo): void {
                $pdo->exec("CREATE TABLE IF NOT EXISTS `donations` (
                    `id` INT AUTO_INCREMENT PRIMARY KEY,
                    `donor_name` VARCHAR(150) NULL,
                    `donor_email` VARCHAR(255) NULL,
                    `donor_phone` VARCHAR(50) NULL,
                    `category` VARCHAR(100) NOT NULL DEFAULT 'Tithe',
                    `amount` DECIMAL(12,2) NOT NULL,
                    `currency` VARCHAR(10) NOT NULL DEFAULT 'NGN',
                    `description` TEXT NULL,
                    `payment_method` ENUM('online', 'manual_bank') NOT NULL DEFAULT 'online',
                    `payment_status` ENUM('pending', 'completed', 'failed') NOT NULL DEFAULT 'pending',
                    `payment_reference` VARCHAR(100) NULL,
                    `receipt_path` VARCHAR(255) NULL,
                    `org_unit_id` INT NULL,
                    `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                    `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
                    INDEX `idx_donation_status` (`payment_status`, `payment_method`),
                    INDEX `idx_donation_category` (`category`),
                    FOREIGN KEY (`org_unit_id`) REFERENCES `org_units`(`id`) ON DELETE SET NULL
                ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4");
            },
            '2026_08_app_download' => function (PDO $pdo): void {
                // Floating "Get it on Google Play" button on the public website.
                // app_download_pages: 'all' or a comma-separated list of paths.
                self::addColumnIfMissing($pdo, 'settings', 'app_download_enabled', "TINYINT(1) NOT NULL DEFAULT 0", 'giving_url');
                self::addColumnIfMissing($pdo, 'settings', 'app_download_url', 'VARCHAR(500) NULL', 'app_download_enabled');
                self::addColumnIfMissing($pdo, 'settings', 'app_download_pages', 'TEXT NULL', 'app_download_url');
            },
            '2026_08_attendance' => function (PDO $pdo): void {
                // Church growth tracking: attendance records + newcomer follow-up.
                $pdo->exec("CREATE TABLE IF NOT EXISTS `attendance_records` (
                    `id` INT AUTO_INCREMENT PRIMARY KEY,
                    `org_unit_id` INT NULL,
                    `service_date` DATE NOT NULL,
                    `service_name` VARCHAR(120) NOT NULL,
                    `topic` VARCHAR(255) NULL,
                    `bible_text` VARCHAR(255) NULL,
                    `male_count` INT NOT NULL DEFAULT 0,
                    `female_count` INT NOT NULL DEFAULT 0,
                    `notes` TEXT NULL,
                    `created_by` INT NULL,
                    `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                    `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
                    INDEX `idx_attendance_unit_date` (`org_unit_id`, `service_date`),
                    FOREIGN KEY (`org_unit_id`) REFERENCES `org_units`(`id`) ON DELETE SET NULL
                ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4");
                $pdo->exec("CREATE TABLE IF NOT EXISTS `newcomers` (
                    `id` INT AUTO_INCREMENT PRIMARY KEY,
                    `org_unit_id` INT NULL,
                    `name` VARCHAR(150) NOT NULL,
                    `whatsapp_phone` VARCHAR(40) NULL,
                    `address` VARCHAR(255) NULL,
                    `gender` ENUM('male','female','other') NULL,
                    `age_group` ENUM('adult','children','youth') NOT NULL DEFAULT 'adult',
                    `attendance_id` INT NULL,
                    `visit_date` DATE NULL,
                    `follow_up_status` ENUM('new','contacted','followed_up','returned','inactive') NOT NULL DEFAULT 'new',
                    `notes` TEXT NULL,
                    `created_by` INT NULL,
                    `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                    `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
                    INDEX `idx_newcomer_unit_status` (`org_unit_id`, `follow_up_status`),
                    FOREIGN KEY (`org_unit_id`) REFERENCES `org_units`(`id`) ON DELETE SET NULL,
                    FOREIGN KEY (`attendance_id`) REFERENCES `attendance_records`(`id`) ON DELETE SET NULL
                ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4");
            },
            '2026_08_backfill_media_units' => function (PDO $pdo): void {
                // Posts created before the org hierarchy existed (or by an admin
                // with no home unit) have org_unit_id = NULL and therefore never
                // show up on any church's unit page. Assign them to the super
                // admin's home unit when set, otherwise to the first parish, so
                // they become visible and can be moved with the Church control.
                $nullCount = (int) $pdo->query('SELECT COUNT(*) FROM media_posts WHERE org_unit_id IS NULL')->fetchColumn();
                if ($nullCount === 0) {
                    return;
                }
                $target = (int) $pdo->query("SELECT org_unit_id FROM users WHERE is_super_admin = 1 AND org_unit_id IS NOT NULL ORDER BY id ASC LIMIT 1")->fetchColumn();
                if ($target <= 0) {
                    $target = (int) $pdo->query("SELECT id FROM org_units WHERE type = 'parish' ORDER BY id ASC LIMIT 1")->fetchColumn();
                }
                if ($target > 0) {
                    $pdo->prepare('UPDATE media_posts SET org_unit_id = ? WHERE org_unit_id IS NULL')->execute([$target]);
                }
            },
            '2026_08_pinned_reels' => function (PDO $pdo): void {
                // Pin reels so they always surface first. Up to 3 active pins per
                // church (org_unit_id); each pin auto-expires after 3 days. The
                // effective pin check everywhere is:
                //   is_pinned = 1 AND pinned_expires_at > NOW()
                self::addColumnIfMissing($pdo, 'media_posts', 'is_pinned', "TINYINT(1) NOT NULL DEFAULT 0", 'org_unit_id');
                self::addColumnIfMissing($pdo, 'media_posts', 'pinned_at', 'DATETIME NULL', 'is_pinned');
                self::addColumnIfMissing($pdo, 'media_posts', 'pinned_expires_at', 'DATETIME NULL', 'pinned_at');
            },
            '2026_08_app_redirect' => function (PDO $pdo): void {
                // "Admin & App only" mode: when enabled, Android phone visitors
                // are sent to the app. 'interstitial' shows a landing page with a
                // Google Play button + a "Continue to website" escape (remembered
                // per browser); 'force' redirects straight to the Play link.
                self::addColumnIfMissing($pdo, 'settings', 'app_redirect_mode', "VARCHAR(12) NOT NULL DEFAULT 'off'", 'app_download_pages');
            },
            '2026_08_attendance_gender' => function (PDO $pdo): void {
                // Attendance now tracks the Youth church by gender (male/female)
                // instead of the whole-church adult/children/youth split. The old
                // columns are left in place (harmless, unused) so the migration
                // never destroys existing data.
                self::addColumnIfMissing($pdo, 'attendance_records', 'male_count', 'INT NOT NULL DEFAULT 0', 'bible_text');
                self::addColumnIfMissing($pdo, 'attendance_records', 'female_count', 'INT NOT NULL DEFAULT 0', 'male_count');
            },
            '2026_08_form_cascade_church' => function (PDO $pdo): void {
                // Form fields now support cascading dropdowns (Province > Zone >
                // Area > Parish) and an auto church-list field that builds the
                // same chained selects live from the org_units hierarchy.
                $pdo->exec("ALTER TABLE `form_fields` MODIFY COLUMN `field_type` ENUM('text','textarea','email','phone','number','date','url','select','radio','checkbox','image','cascade','church') NOT NULL DEFAULT 'text'");
            },
            '2026_08_export_files' => function (PDO $pdo): void {
                // Server-hosted shareable CSV exports (Google-Forms style): each
                // export is saved to storage/exports and exposed via an
                // unguessable /export/{token} link that anyone with the link can
                // view or download. Admins generate/remove these from the panel.
                $pdo->exec("CREATE TABLE IF NOT EXISTS `export_files` (
                    `id` INT AUTO_INCREMENT PRIMARY KEY,
                    `kind` VARCHAR(40) NOT NULL DEFAULT 'csv',
                    `title` VARCHAR(255) NULL,
                    `filename` VARCHAR(255) NOT NULL,
                    `token` VARCHAR(64) NOT NULL UNIQUE,
                    `path` VARCHAR(255) NOT NULL,
                    `form_id` INT NULL,
                    `created_by` INT NULL,
                    `downloads` INT NOT NULL DEFAULT 0,
                    `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                    FOREIGN KEY (`form_id`) REFERENCES `forms`(`id`) ON DELETE CASCADE,
                    FOREIGN KEY (`created_by`) REFERENCES `users`(`id`) ON DELETE SET NULL,
                    INDEX `idx_export_form` (`form_id`)
                ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4");
            },
            '2026_08_form_visibility' => function (PDO $pdo): void {
                // Forms can now be public (anyone with the link) or private
                // (link + password). password_hash is only used when private.
                self::addColumnIfMissing($pdo, 'forms', 'visibility', "ENUM('public','private') NOT NULL DEFAULT 'public'", 'is_active');
                self::addColumnIfMissing($pdo, 'forms', 'password_hash', 'VARCHAR(255) NULL', 'visibility');
            },
            '2026_08_form_datetime_fields' => function (PDO $pdo): void {
                // New form field types: 'time' and 'datetime' (date and time).
                $pdo->exec("ALTER TABLE `form_fields` MODIFY COLUMN `field_type` ENUM('text','textarea','email','phone','number','date','url','select','radio','checkbox','image','cascade','church','time','datetime') NOT NULL DEFAULT 'text'");
            },
            '2026_08_church_registration' => function (PDO $pdo): void {
                // Public church-admin self-registration, pending super-admin approval.
                $pdo->exec("CREATE TABLE IF NOT EXISTS `pending_registrations` (
                    `id` INT AUTO_INCREMENT PRIMARY KEY,
                    `name` VARCHAR(150) NOT NULL,
                    `email` VARCHAR(150) NOT NULL,
                    `phone` VARCHAR(45) NULL,
                    `username` VARCHAR(100) NOT NULL,
                    `password_hash` VARCHAR(255) NOT NULL,
                    `province_id` INT NULL,
                    `zone_id` INT NULL,
                    `area_id` INT NULL,
                    `parish_name` VARCHAR(150) NULL,
                    `parish_id` INT NULL,
                    `status` ENUM('pending','approved','rejected') NOT NULL DEFAULT 'pending',
                    `reviewed_by` INT NULL,
                    `reviewed_at` TIMESTAMP NULL,
                    `reject_reason` VARCHAR(500) NULL,
                    `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                    FOREIGN KEY (`province_id`) REFERENCES `org_units`(`id`) ON DELETE SET NULL,
                    FOREIGN KEY (`zone_id`) REFERENCES `org_units`(`id`) ON DELETE SET NULL,
                    FOREIGN KEY (`area_id`) REFERENCES `org_units`(`id`) ON DELETE SET NULL,
                    FOREIGN KEY (`parish_id`) REFERENCES `org_units`(`id`) ON DELETE SET NULL,
                    INDEX `idx_reg_status` (`status`, `created_at`)
                ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4");

                // Publicly-flagged church name corrections, approved/rejected by the super admin.
                $pdo->exec("CREATE TABLE IF NOT EXISTS `church_name_flags` (
                    `id` INT AUTO_INCREMENT PRIMARY KEY,
                    `org_unit_id` INT NULL,
                    `current_name` VARCHAR(150) NOT NULL,
                    `suggested_name` VARCHAR(150) NOT NULL,
                    `status` ENUM('pending','approved','rejected') NOT NULL DEFAULT 'pending',
                    `reported_by` VARCHAR(150) NULL,
                    `reviewed_by` INT NULL,
                    `reviewed_at` TIMESTAMP NULL,
                    `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                    FOREIGN KEY (`org_unit_id`) REFERENCES `org_units`(`id`) ON DELETE SET NULL,
                    FOREIGN KEY (`reviewed_by`) REFERENCES `users`(`id`) ON DELETE SET NULL,
                    INDEX `idx_flag_status` (`status`, `created_at`)
                ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4");

                // All church names are stored in CAPS.
                $pdo->exec('UPDATE org_units SET name = UPPER(name)');
            },
            '2026_08_social_twitter' => function (PDO $pdo): void {
                self::addColumnIfMissing($pdo, 'settings', 'twitter_url', 'VARCHAR(255) NULL', 'tiktok_url');
            },
            '2026_08_go_declaration' => function (PDO $pdo): void {
                self::addColumnIfMissing($pdo, 'settings', 'go_declaration_enabled', 'TINYINT(1) NOT NULL DEFAULT 0', 'twitter_url');
                self::addColumnIfMissing($pdo, 'settings', 'go_declaration_title', "VARCHAR(150) NULL DEFAULT 'G.O. Declaration'", 'go_declaration_enabled');
                self::addColumnIfMissing($pdo, 'settings', 'go_declaration_text', 'TEXT NULL', 'go_declaration_title');
                self::addColumnIfMissing($pdo, 'settings', 'go_declaration_mode', "VARCHAR(20) NOT NULL DEFAULT 'marquee'", 'go_declaration_text');
            },
            '2026_08_cpanel_email' => function (PDO $pdo): void {
                // Automatic corporate email creation for approved church admins.
                self::addColumnIfMissing($pdo, 'settings', 'email_cpanel_enabled', 'TINYINT(1) NOT NULL DEFAULT 0', 'smtp_from');
                self::addColumnIfMissing($pdo, 'settings', 'email_cpanel_host', 'VARCHAR(255) NULL', 'email_cpanel_enabled');
                self::addColumnIfMissing($pdo, 'settings', 'email_cpanel_user', 'VARCHAR(100) NULL', 'email_cpanel_host');
                self::addColumnIfMissing($pdo, 'settings', 'email_cpanel_token', 'VARCHAR(255) NULL', 'email_cpanel_user');
                self::addColumnIfMissing($pdo, 'settings', 'email_domain', 'VARCHAR(190) NULL', 'email_cpanel_token');
                self::addColumnIfMissing($pdo, 'settings', 'email_default_quota', 'INT NOT NULL DEFAULT 500', 'email_domain');

                // Registrants pick a role; their chosen password is stored encrypted
                // (recoverable only at approval time, for the cPanel email account).
                self::addColumnIfMissing($pdo, 'pending_registrations', 'role', "VARCHAR(20) NOT NULL DEFAULT 'admin'", 'status');
                self::addColumnIfMissing($pdo, 'pending_registrations', 'alt_email', 'VARCHAR(190) NULL', 'email');
                self::addColumnIfMissing($pdo, 'pending_registrations', 'password_enc', 'TEXT NULL', 'password_hash');
                self::addColumnIfMissing($pdo, 'pending_registrations', 'email_created', 'TINYINT(1) NOT NULL DEFAULT 0', 'status');
                self::addColumnIfMissing($pdo, 'pending_registrations', 'created_email', 'VARCHAR(190) NULL', 'email_created');
            },
            '2026_08_security_restore' => function (PDO $pdo): void {
                self::addColumnIfMissing($pdo, 'users', 'alt_email', 'VARCHAR(190) NULL', 'email');
                self::addColumnIfMissing($pdo, 'users', 'unblock_pin_hash', 'VARCHAR(255) NULL', 'password');
                self::addColumnIfMissing($pdo, 'users', 'reset_otp', 'VARCHAR(10) NULL', 'unblock_pin_hash');
                self::addColumnIfMissing($pdo, 'users', 'reset_otp_expires_at', 'DATETIME NULL', 'reset_otp');
                self::addColumnIfMissing($pdo, 'pending_registrations', 'unblock_pin_hash', 'VARCHAR(255) NULL', 'password_hash');
            },
            '2026_08_advertising_system' => function (PDO $pdo): void {
                // Ad duration presets managed by super admin
                $pdo->exec("CREATE TABLE IF NOT EXISTS `ad_durations` (
                    `id` INT AUTO_INCREMENT PRIMARY KEY,
                    `title` VARCHAR(100) NOT NULL,
                    `days` INT NOT NULL,
                    `price` DECIMAL(10,2) NOT NULL DEFAULT 0.00,
                    `is_free` TINYINT(1) NOT NULL DEFAULT 0,
                    `display_frequency` VARCHAR(20) NOT NULL DEFAULT '5_min',
                    `is_active` TINYINT(1) NOT NULL DEFAULT 1,
                    `sort_order` INT NOT NULL DEFAULT 0,
                    `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP
                ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4");
                self::addColumnIfMissing($pdo, 'ad_durations', 'price', 'DECIMAL(10,2) NOT NULL DEFAULT 0.00', 'days');
                self::addColumnIfMissing($pdo, 'ad_durations', 'is_free', 'TINYINT(1) NOT NULL DEFAULT 0', 'price');
                self::addColumnIfMissing($pdo, 'ad_durations', 'display_frequency', "VARCHAR(20) NOT NULL DEFAULT '5_min'", 'is_free');

                // Seed default ad durations if empty
                if ((int) $pdo->query('SELECT COUNT(*) FROM ad_durations')->fetchColumn() === 0) {
                    $pdo->exec("INSERT INTO ad_durations (title, days, price, is_free, display_frequency, sort_order) VALUES
                        ('Free Trial (7 Days)', 7, 0.00, 1, 'once_daily', 1),
                        ('7 Days Premium', 7, 5000.00, 0, '5_min', 2),
                        ('14 Days Premium', 14, 9000.00, 0, '5_min', 3),
                        ('30 Days Premium', 30, 15000.00, 0, '5_min', 4)");
                }

                // Ad publishers (advertisers)
                $pdo->exec("CREATE TABLE IF NOT EXISTS `ad_publishers` (
                    `id` INT AUTO_INCREMENT PRIMARY KEY,
                    `name` VARCHAR(150) NOT NULL,
                    `email` VARCHAR(150) NOT NULL,
                    `phone` VARCHAR(45) NULL,
                    `token` VARCHAR(64) NOT NULL UNIQUE,
                    `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                    INDEX `idx_pub_email` (`email`)
                ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4");
                self::addColumnIfMissing($pdo, 'ad_publishers', 'phone', 'VARCHAR(45) NULL', 'email');
                self::addColumnIfMissing($pdo, 'ad_publishers', 'token', 'VARCHAR(64) NULL', 'phone');

                // Advertisements table with payment tracking
                $pdo->exec("CREATE TABLE IF NOT EXISTS `ads` (
                    `id` INT AUTO_INCREMENT PRIMARY KEY,
                    `publisher_id` INT NOT NULL,
                    `title` VARCHAR(200) NOT NULL,
                    `media_type` ENUM('image','video') NOT NULL,
                    `file_path` VARCHAR(255) NOT NULL,
                    `thumbnail_path` VARCHAR(255) NULL,
                    `destination_url` VARCHAR(500) NULL,
                    `target_platform` ENUM('web','app','both') NOT NULL DEFAULT 'both',
                    `duration_days` INT NOT NULL,
                    `price` DECIMAL(10,2) NOT NULL DEFAULT 0.00,
                    `is_free` TINYINT(1) NOT NULL DEFAULT 0,
                    `display_frequency` VARCHAR(20) NOT NULL DEFAULT '5_min',
                    `payment_status` ENUM('unpaid','pending_review','paid') NOT NULL DEFAULT 'unpaid',
                    `payment_method` ENUM('online','manual','free') NOT NULL DEFAULT 'free',
                    `payment_proof_path` VARCHAR(255) NULL,
                    `payment_reference` VARCHAR(100) NULL,
                    `status` ENUM('pending','approved','rejected') NOT NULL DEFAULT 'pending',
                    `start_at` DATETIME NULL,
                    `expires_at` DATETIME NULL,
                    `views_count` INT NOT NULL DEFAULT 0,
                    `clicks_count` INT NOT NULL DEFAULT 0,
                    `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                    `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
                    FOREIGN KEY (`publisher_id`) REFERENCES `ad_publishers`(`id`) ON DELETE CASCADE,
                    INDEX `idx_ad_status_expires` (`status`, `start_at`, `expires_at`, `target_platform`)
                ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4");
                self::addColumnIfMissing($pdo, 'ads', 'price', 'DECIMAL(10,2) NOT NULL DEFAULT 0.00', 'duration_days');
                self::addColumnIfMissing($pdo, 'ads', 'is_free', 'TINYINT(1) NOT NULL DEFAULT 0', 'price');
                self::addColumnIfMissing($pdo, 'ads', 'display_frequency', "VARCHAR(20) NOT NULL DEFAULT '5_min'", 'is_free');
                self::addColumnIfMissing($pdo, 'ads', 'payment_status', "ENUM('unpaid','pending_review','paid') NOT NULL DEFAULT 'unpaid'", 'display_frequency');
                self::addColumnIfMissing($pdo, 'ads', 'payment_method', "ENUM('online','manual','free') NOT NULL DEFAULT 'free'", 'payment_status');
                self::addColumnIfMissing($pdo, 'ads', 'payment_proof_path', 'VARCHAR(255) NULL', 'payment_method');
                self::addColumnIfMissing($pdo, 'ads', 'payment_reference', 'VARCHAR(100) NULL', 'payment_proof_path');

                // Ad interaction logs
                $pdo->exec("CREATE TABLE IF NOT EXISTS `ad_events` (
                    `id` INT AUTO_INCREMENT PRIMARY KEY,
                    `ad_id` INT NOT NULL,
                    `event_type` ENUM('view','click') NOT NULL,
                    `platform` VARCHAR(20) NOT NULL DEFAULT 'web',
                    `ip_address` VARCHAR(45) NULL,
                    `user_agent` VARCHAR(255) NULL,
                    `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                    FOREIGN KEY (`ad_id`) REFERENCES `ads`(`id`) ON DELETE CASCADE,
                    INDEX `idx_ad_event_time` (`ad_id`, `event_type`, `created_at`)
                ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4");

                // Transaction history table for ad payments
                $pdo->exec("CREATE TABLE IF NOT EXISTS `ad_payments` (
                    `id` INT AUTO_INCREMENT PRIMARY KEY,
                    `ad_id` INT NOT NULL,
                    `publisher_id` INT NOT NULL,
                    `amount` DECIMAL(10,2) NOT NULL,
                    `payment_method` ENUM('online','manual','free') NOT NULL,
                    `reference` VARCHAR(100) NOT NULL,
                    `status` ENUM('pending','success','failed') NOT NULL DEFAULT 'pending',
                    `proof_path` VARCHAR(255) NULL,
                    `gateway_response` TEXT NULL,
                    `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                    FOREIGN KEY (`ad_id`) REFERENCES `ads`(`id`) ON DELETE CASCADE,
                    FOREIGN KEY (`publisher_id`) REFERENCES `ad_publishers`(`id`) ON DELETE CASCADE
                ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4");

                // Settings for Payhub, Manual Payment & Ad Display Frequencies
                self::addColumnIfMissing($pdo, 'settings', 'payhub_enabled', 'TINYINT(1) NOT NULL DEFAULT 0', 'app_redirect_mode');
                self::addColumnIfMissing($pdo, 'settings', 'payhub_public_key', 'VARCHAR(255) NULL', 'payhub_enabled');
                self::addColumnIfMissing($pdo, 'settings', 'payhub_secret_key', 'VARCHAR(255) NULL', 'payhub_public_key');
                self::addColumnIfMissing($pdo, 'settings', 'manual_payment_enabled', 'TINYINT(1) NOT NULL DEFAULT 1', 'payhub_secret_key');
                self::addColumnIfMissing($pdo, 'settings', 'manual_payment_instructions', 'TEXT NULL', 'manual_payment_enabled');
                self::addColumnIfMissing($pdo, 'settings', 'ad_display_frequency', "VARCHAR(20) NOT NULL DEFAULT '5_min'", 'manual_payment_instructions');
                self::addColumnIfMissing($pdo, 'settings', 'free_ad_frequency', "VARCHAR(20) NOT NULL DEFAULT 'once_daily'", 'ad_display_frequency');
                self::addColumnIfMissing($pdo, 'pages', 'parent_id', 'INT NULL DEFAULT NULL', 'id');
            },
            '2026_08_testimonies' => function (PDO $pdo): void {
                $pdo->exec("CREATE TABLE IF NOT EXISTS `testimonies` (
                    `id` INT AUTO_INCREMENT PRIMARY KEY,
                    `unit_id` INT NULL DEFAULT NULL,
                    `name` VARCHAR(150) NOT NULL,
                    `email` VARCHAR(190) NULL,
                    `phone` VARCHAR(50) NULL,
                    `title` VARCHAR(255) NOT NULL,
                    `content` TEXT NOT NULL,
                    `media_url` VARCHAR(500) NULL,
                    `status` VARCHAR(20) NOT NULL DEFAULT 'pending',
                    `submitted_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                    `approved_at` TIMESTAMP NULL DEFAULT NULL,
                    INDEX `idx_testimony_status` (`status`, `submitted_at`),
                    INDEX `idx_testimony_unit` (`unit_id`)
                ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4");
            },
            '2026_09_unit_levels' => function (PDO $pdo): void {
                // Configurable hierarchy levels. `type` is the stable key stored in
                // org_units.type; `label`/`plural` are what admins see, and
                // `sort_order` is the depth (1 = top level, ascending = deeper).
                // The super admin can rename, reorder, add or remove levels from
                // Admin → Unit Levels, so nothing may hard-code the four names.
                $pdo->exec("CREATE TABLE IF NOT EXISTS `unit_levels` (
                    `id` INT AUTO_INCREMENT PRIMARY KEY,
                    `type` VARCHAR(40) NOT NULL,
                    `label` VARCHAR(60) NOT NULL,
                    `plural` VARCHAR(60) NOT NULL,
                    `sort_order` INT NOT NULL DEFAULT 0,
                    `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                    UNIQUE KEY `uniq_unit_level_type` (`type`),
                    UNIQUE KEY `uniq_unit_level_sort` (`sort_order`)
                ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4");

                // Seed the classic RCCG hierarchy once (idempotent thanks to the
                // unique key on `type`).
                $seed = $pdo->prepare('INSERT IGNORE INTO unit_levels (type, label, plural, sort_order) VALUES (?, ?, ?, ?)');
                foreach ([
                    ['province', 'Province', 'Provinces', 1],
                    ['zone', 'Zone', 'Zones', 2],
                    ['area', 'Area', 'Areas', 3],
                    ['parish', 'Parish', 'Parishes', 4],
                ] as $level) {
                    $seed->execute($level);
                }

                // `type` can no longer be a fixed ENUM now that levels are editable.
                $col = $pdo->prepare('SELECT DATA_TYPE FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = ? AND COLUMN_NAME = ?');
                $col->execute(['org_units', 'type']);
                if (strtolower((string) $col->fetchColumn()) === 'enum') {
                    $pdo->exec("ALTER TABLE `org_units` MODIFY COLUMN `type` VARCHAR(40) NOT NULL");
                }

                // Registrations can now capture any depth of hierarchy.
                $tbl = $pdo->prepare('SELECT COUNT(*) FROM information_schema.TABLES WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = ?');
                $tbl->execute(['pending_registrations']);
                if ((int) $tbl->fetchColumn() > 0) {
                    self::addColumnIfMissing($pdo, 'pending_registrations', 'unit_path', 'TEXT NULL', 'parish_id');
                }
            },

            // Phase 0 of the SaaS roadmap: tenants. The first tenant is seeded
            // from the current settings row so a single-church install keeps
            // working untouched — `settings.tenant_id` stays NULL there, which
            // still means "shared defaults for everyone".
            '2026_10_tenants' => function (PDO $pdo): void {
                $pdo->exec("CREATE TABLE IF NOT EXISTS `tenants` (
                    `id` INT AUTO_INCREMENT PRIMARY KEY,
                    `name` VARCHAR(150) NOT NULL,
                    `slug` VARCHAR(80) NOT NULL,
                    `domain` VARCHAR(190) NULL,
                    `subdomain` VARCHAR(80) NULL,
                    `logo_path` VARCHAR(255) NULL,
                    `primary_colour` VARCHAR(20) NULL,
                    `plan` VARCHAR(40) NOT NULL DEFAULT 'standard',
                    `is_active` TINYINT(1) NOT NULL DEFAULT 1,
                    `is_default` TINYINT(1) NOT NULL DEFAULT 0,
                    `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                    UNIQUE KEY `uniq_tenant_slug` (`slug`),
                    UNIQUE KEY `uniq_tenant_domain` (`domain`),
                    UNIQUE KEY `uniq_tenant_subdomain` (`subdomain`)
                ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4");

                self::addColumnIfMissing($pdo, 'settings', 'tenant_id', 'INT NULL', 'id');
                self::addIndexIfMissing($pdo, 'settings', 'uniq_settings_tenant', 'UNIQUE KEY `uniq_settings_tenant` (`tenant_id`)');

                // A tenant must always exist so Tenant::current() can resolve.
                if ((int) $pdo->query('SELECT COUNT(*) FROM tenants')->fetchColumn() === 0) {
                    $title = 'Default Church';
                    try {
                        $existing = $pdo->query('SELECT site_title FROM settings WHERE tenant_id IS NULL ORDER BY id ASC LIMIT 1')->fetchColumn();
                        if (is_string($existing) && $existing !== '') {
                            $title = $existing;
                        }
                    } catch (Throwable $e) {
                        // Fresh install with an empty settings table — keep the fallback.
                    }
                    $pdo->prepare('INSERT INTO tenants (name, slug, is_default) VALUES (?, ?, 1)')
                        ->execute([$title, 'default']);
                }
            },

            // Comment moderation. Existing comments default to 'approved' so
            // nothing already published disappears when this lands.
            '2026_11_comment_moderation' => function (PDO $pdo): void {
                self::addColumnIfMissing($pdo, 'post_comments', 'status', "ENUM('approved','pending','rejected','spam') NOT NULL DEFAULT 'approved'", 'is_published');
                self::addColumnIfMissing($pdo, 'post_comments', 'moderated_by', 'INT NULL', 'status');
                self::addColumnIfMissing($pdo, 'post_comments', 'moderated_at', 'DATETIME NULL', 'moderated_by');
                self::addColumnIfMissing($pdo, 'post_comments', 'moderator_note', 'VARCHAR(255) NULL', 'moderated_at');
                self::addColumnIfMissing($pdo, 'post_comments', 'report_count', 'INT NOT NULL DEFAULT 0', 'moderator_note');
                self::addColumnIfMissing($pdo, 'post_comments', 'is_flagged', 'TINYINT(1) NOT NULL DEFAULT 0', 'report_count');
                self::addColumnIfMissing($pdo, 'post_comments', 'held_reason', 'VARCHAR(255) NULL', 'is_flagged');
                self::addIndexIfMissing($pdo, 'post_comments', 'idx_comment_status', 'INDEX `idx_comment_status` (`status`, `created_at`)');
                self::addIndexIfMissing($pdo, 'post_comments', 'idx_comment_flagged', 'INDEX `idx_comment_flagged` (`is_flagged`, `report_count`)');

                self::addColumnIfMissing($pdo, 'settings', 'comments_moderation', "VARCHAR(20) NOT NULL DEFAULT 'off'", 'license_key');
                self::addColumnIfMissing($pdo, 'settings', 'comments_flag_threshold', 'INT NOT NULL DEFAULT 3', 'comments_moderation');

                $pdo->exec("CREATE TABLE IF NOT EXISTS `comment_reports` (
                    `id` INT AUTO_INCREMENT PRIMARY KEY,
                    `comment_id` INT NOT NULL,
                    `fingerprint_hash` VARCHAR(64) NULL,
                    `reason` VARCHAR(255) NULL,
                    `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                    UNIQUE KEY `uniq_comment_report` (`comment_id`, `fingerprint_hash`),
                    FOREIGN KEY (`comment_id`) REFERENCES `post_comments`(`id`) ON DELETE CASCADE
                ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4");

                $pdo->exec("CREATE TABLE IF NOT EXISTS `comment_blocklist` (
                    `id` INT AUTO_INCREMENT PRIMARY KEY,
                    `tenant_id` INT NULL,
                    `kind` ENUM('block','spam') NOT NULL DEFAULT 'block',
                    `word` VARCHAR(100) NOT NULL,
                    `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                    UNIQUE KEY `uniq_blocklist_word` (`tenant_id`, `kind`, `word`),
                    INDEX `idx_blocklist_kind` (`kind`)
                ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4");
            },

            // Analytics. Raw events are pruned on a retention window; the daily
            // roll-up is kept indefinitely so long-range trends survive.
            '2026_12_analytics' => function (PDO $pdo): void {
                $pdo->exec("CREATE TABLE IF NOT EXISTS `analytics_events` (
                    `id` BIGINT AUTO_INCREMENT PRIMARY KEY,
                    `tenant_id` INT NOT NULL DEFAULT 0,
                    `occurred_at` DATETIME NOT NULL,
                    `event` VARCHAR(60) NOT NULL,
                    `path` VARCHAR(255) NULL,
                    `org_unit_id` INT NULL,
                    `entity_type` VARCHAR(30) NULL,
                    `entity_id` INT NULL,
                    `device` VARCHAR(10) NOT NULL DEFAULT 'web',
                    `session_hash` VARCHAR(64) NULL,
                    `referrer_host` VARCHAR(120) NULL,
                    `country` VARCHAR(2) NULL,
                    `meta` VARCHAR(255) NULL,
                    INDEX `idx_ae_time` (`occurred_at`),
                    INDEX `idx_ae_event_time` (`event`, `occurred_at`),
                    INDEX `idx_ae_tenant_time` (`tenant_id`, `occurred_at`),
                    INDEX `idx_ae_entity` (`entity_type`, `entity_id`),
                    INDEX `idx_ae_session` (`session_hash`, `occurred_at`)
                ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4");

                $pdo->exec("CREATE TABLE IF NOT EXISTS `analytics_daily` (
                    `id` INT AUTO_INCREMENT PRIMARY KEY,
                    `tenant_id` INT NOT NULL DEFAULT 0,
                    `day` DATE NOT NULL,
                    `event` VARCHAR(60) NOT NULL,
                    `device` VARCHAR(10) NOT NULL DEFAULT 'web',
                    `entity_type` VARCHAR(30) NOT NULL DEFAULT '',
                    `entity_id` INT NOT NULL DEFAULT 0,
                    `org_unit_id` INT NOT NULL DEFAULT 0,
                    `hits` INT NOT NULL DEFAULT 0,
                    UNIQUE KEY `uniq_analytics_day` (`tenant_id`, `day`, `event`, `device`, `entity_type`, `entity_id`, `org_unit_id`),
                    INDEX `idx_ad_day` (`day`),
                    INDEX `idx_ad_event_day` (`event`, `day`)
                ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4");

                self::addColumnIfMissing($pdo, 'settings', 'analytics_enabled', 'TINYINT(1) NOT NULL DEFAULT 1', 'comments_flag_threshold');
                self::addColumnIfMissing($pdo, 'settings', 'analytics_retention_days', 'INT NOT NULL DEFAULT 180', 'analytics_enabled');
            },

            // RSVP. `rsvp_mode` defaults to 'legacy', which means "keep using
            // rsvp_enabled/rsvp_url", so every existing event behaves unchanged
            // until an admin deliberately picks a different mode.
            '2026_13_event_rsvp' => function (PDO $pdo): void {
                self::addColumnIfMissing($pdo, 'events', 'rsvp_mode', "ENUM('legacy','off','external','internal') NOT NULL DEFAULT 'legacy'", 'rsvp_url');
                self::addColumnIfMissing($pdo, 'events', 'max_capacity', 'INT NOT NULL DEFAULT 0', 'rsvp_mode');
                self::addColumnIfMissing($pdo, 'events', 'allow_guests', 'TINYINT(1) NOT NULL DEFAULT 1', 'max_capacity');
                self::addColumnIfMissing($pdo, 'events', 'waitlist_enabled', 'TINYINT(1) NOT NULL DEFAULT 1', 'allow_guests');
                self::addColumnIfMissing($pdo, 'events', 'rsvp_closes_at', 'DATETIME NULL', 'waitlist_enabled');

                $pdo->exec("CREATE TABLE IF NOT EXISTS `event_rsvps` (
                    `id` INT AUTO_INCREMENT PRIMARY KEY,
                    `event_id` INT NOT NULL,
                    `name` VARCHAR(150) NOT NULL,
                    `email` VARCHAR(190) NULL,
                    `phone` VARCHAR(45) NULL,
                    `guests` INT NOT NULL DEFAULT 0,
                    `status` ENUM('going','maybe','declined','waitlist','cancelled') NOT NULL DEFAULT 'going',
                    `token` VARCHAR(64) NOT NULL,
                    `note` VARCHAR(500) NULL,
                    `fingerprint_hash` VARCHAR(64) NULL,
                    `checked_in` TINYINT(1) NOT NULL DEFAULT 0,
                    `checked_in_at` DATETIME NULL,
                    `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                    `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
                    UNIQUE KEY `uniq_rsvp_token` (`token`),
                    UNIQUE KEY `uniq_rsvp_event_email` (`event_id`, `email`),
                    INDEX `idx_rsvp_event_status` (`event_id`, `status`),
                    INDEX `idx_rsvp_email` (`email`),
                    FOREIGN KEY (`event_id`) REFERENCES `events`(`id`) ON DELETE CASCADE
                ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4");
            },

            // Prayer wall. `is_anonymous` is the only thing the public wall trusts
            // — never the absence of a name — so a request that asked to stay
            // anonymous keeps its name for the pastoral team but is never shown.
            '2026_14_prayer_wall' => function (PDO $pdo): void {
                self::addColumnIfMissing($pdo, 'prayer_requests', 'tenant_id', 'INT NULL', 'id');
                self::addColumnIfMissing($pdo, 'prayer_requests', 'increment_count', 'INT NOT NULL DEFAULT 0', 'is_public');
                self::addColumnIfMissing($pdo, 'prayer_requests', 'is_anonymous', 'TINYINT(1) NOT NULL DEFAULT 0', 'increment_count');
                self::addColumnIfMissing($pdo, 'prayer_requests', 'is_featured', 'TINYINT(1) NOT NULL DEFAULT 0', 'is_anonymous');
                self::addColumnIfMissing($pdo, 'prayer_requests', 'answered_at', 'DATETIME NULL', 'is_featured');
                self::addColumnIfMissing($pdo, 'prayer_requests', 'answer_note', 'TEXT NULL', 'answered_at');
                self::addIndexIfMissing($pdo, 'prayer_requests', 'idx_prayer_wall', 'INDEX `idx_prayer_wall` (`tenant_id`, `is_public`, `status`, `created_at`)');
                self::addIndexIfMissing($pdo, 'prayer_requests', 'idx_prayer_answered', 'INDEX `idx_prayer_answered` (`tenant_id`, `answered_at`)');

                // Requests that predate tenancy belong to the default church, so a
                // plain `tenant_id = ?` read never has to special-case NULL.
                try {
                    $defaultTenant = (int) $pdo->query('SELECT id FROM tenants WHERE is_default = 1 ORDER BY id ASC LIMIT 1')->fetchColumn();
                    if ($defaultTenant > 0) {
                        $pdo->prepare('UPDATE prayer_requests SET tenant_id = ? WHERE tenant_id IS NULL')->execute([$defaultTenant]);
                    }
                } catch (Throwable $e) {
                    // No tenants table yet — nothing to attribute the rows to.
                }

                $pdo->exec("CREATE TABLE IF NOT EXISTS `prayer_participants` (
                    `id` INT AUTO_INCREMENT PRIMARY KEY,
                    `tenant_id` INT NULL,
                    `request_id` INT NOT NULL,
                    `session_hash` VARCHAR(64) NOT NULL,
                    `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                    UNIQUE KEY `uniq_prayer_participant` (`request_id`, `session_hash`),
                    INDEX `idx_pp_request` (`request_id`),
                    FOREIGN KEY (`request_id`) REFERENCES `prayer_requests`(`id`) ON DELETE CASCADE
                ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4");
            },

            // Level-aware notification targeting. `target_unit_id` records the unit
            // the sender actually picked — any level, not just a church — and
            // `target_level` snapshots its type, because level names are configurable
            // and may be renamed later. NULL means "every unit in the sender's scope",
            // which is how every notification sent before this landed is treated.
            '2026_15_notification_targeting' => function (PDO $pdo): void {
                self::addColumnIfMissing($pdo, 'notifications', 'target_unit_id', 'INT NULL', 'body');
                self::addColumnIfMissing($pdo, 'notifications', 'target_level', 'VARCHAR(40) NULL', 'target_unit_id');
                self::addIndexIfMissing($pdo, 'notifications', 'idx_notifications_target', 'INDEX `idx_notifications_target` (`target_unit_id`)');
            },

            // Backup retention and the optional off-site copy directory. A single
            // wide settings row means these are plain columns, not key/value pairs.
            '2026_16_backups' => function (PDO $pdo): void {
                self::addColumnIfMissing($pdo, 'settings', 'backup_retention_days', 'INT NOT NULL DEFAULT 14', 'analytics_retention_days');
                self::addColumnIfMissing($pdo, 'settings', 'backup_offsite_path', 'VARCHAR(255) NULL', 'backup_retention_days');
            },

            // SMS messaging hub, foundation. Additive only: phone columns are nullable
            // so every existing row keeps working, and the settings columns are left at
            // their defaults so nothing sends until an admin connects a gateway.
            '2026_17_sms_foundation' => function (PDO $pdo): void {
                // Contact sources that already hold a phone number somewhere else.
                self::addColumnIfMissing($pdo, 'users', 'phone', 'VARCHAR(32) NULL', 'email');
                self::addColumnIfMissing($pdo, 'newsletter_subscribers', 'phone', 'VARCHAR(32) NULL', 'email');
                self::addColumnIfMissing($pdo, 'newsletter_subscribers', 'sms_consent', 'TINYINT(1) NOT NULL DEFAULT 0', 'phone');
                self::addColumnIfMissing($pdo, 'device_tokens', 'phone', 'VARCHAR(32) NULL', 'org_unit_id');

                // Gateway settings. The token is stored encrypted and never rendered
                // in full; `sms_default_country` drives number normalisation.
                self::addColumnIfMissing($pdo, 'settings', 'sms_token', 'TEXT NULL', 'backup_offsite_path');
                self::addColumnIfMissing($pdo, 'settings', 'sms_default_country', "VARCHAR(4) NOT NULL DEFAULT '234'", 'sms_token');
                self::addColumnIfMissing($pdo, 'settings', 'sms_default_sender_id', 'VARCHAR(11) NULL', 'sms_default_country');
                self::addColumnIfMissing($pdo, 'settings', 'sms_sender_display_name', 'VARCHAR(60) NULL', 'sms_default_sender_id');
                self::addColumnIfMissing($pdo, 'settings', 'sms_quiet_start', 'TINYINT NOT NULL DEFAULT 7', 'sms_sender_display_name');
                self::addColumnIfMissing($pdo, 'settings', 'sms_quiet_end', 'TINYINT NOT NULL DEFAULT 20', 'sms_quiet_start');
                self::addColumnIfMissing($pdo, 'settings', 'sms_daily_unit_cap', 'INT NOT NULL DEFAULT 0', 'sms_quiet_end');
                self::addColumnIfMissing($pdo, 'settings', 'sms_sender_cap', 'INT NOT NULL DEFAULT 0', 'sms_daily_unit_cap');
                self::addColumnIfMissing($pdo, 'settings', 'sms_batch_size', 'INT NOT NULL DEFAULT 100', 'sms_sender_cap');
                self::addColumnIfMissing($pdo, 'settings', 'sms_allow_unit_sending', 'TINYINT(1) NOT NULL DEFAULT 1', 'sms_batch_size');
                self::addColumnIfMissing($pdo, 'settings', 'sms_optout_footer', "VARCHAR(160) NOT NULL DEFAULT 'Reply STOP to opt out.'", 'sms_allow_unit_sending');
                self::addColumnIfMissing($pdo, 'settings', 'sms_log_retention_days', 'INT NOT NULL DEFAULT 30', 'sms_optout_footer');

                // Country rules, so a number is validated against its own country rather
                // than silently mangled. Seeded with the markets this is likely to serve.
                $pdo->exec("CREATE TABLE IF NOT EXISTS `sms_countries` (
                    `id` INT AUTO_INCREMENT PRIMARY KEY,
                    `dial_code` VARCHAR(4) NOT NULL,
                    `name` VARCHAR(80) NOT NULL,
                    `national_length` INT NOT NULL COMMENT 'Digits after the dial code for a national number',
                    `trunk_prefix` VARCHAR(2) NOT NULL DEFAULT '0' COMMENT 'National prefix stripped before the dial code is applied',
                    `is_active` TINYINT(1) NOT NULL DEFAULT 1,
                    UNIQUE KEY `uniq_sms_country` (`dial_code`)
                ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4");

                $countries = [
                    ['234', 'Nigeria', 10, '0'],
                    ['233', 'Ghana', 9, '0'],
                    ['254', 'Kenya', 9, '0'],
                    ['256', 'Uganda', 9, '0'],
                    ['255', 'Tanzania', 9, '0'],
                    ['27', 'South Africa', 9, '0'],
                    ['263', 'Zimbabwe', 9, '0'],
                    ['251', 'Ethiopia', 9, '0'],
                    ['250', 'Rwanda', 9, '0'],
                    ['231', 'Liberia', 8, '0'],
                    ['232', 'Sierra Leone', 8, '0'],
                    ['220', 'Gambia', 7, '0'],
                    ['1', 'United States / Canada', 10, '1'],
                    ['44', 'United Kingdom', 10, '0'],
                    ['353', 'Ireland', 9, '0'],
                    ['61', 'Australia', 9, '0'],
                    ['971', 'United Arab Emirates', 9, '0'],
                    ['91', 'India', 10, '0'],
                ];
                $seedCountry = $pdo->prepare('INSERT IGNORE INTO sms_countries (dial_code, name, national_length, trunk_prefix) VALUES (?, ?, ?, ?)');
                foreach ($countries as $country) {
                    $seedCountry->execute($country);
                }

                $pdo->exec("CREATE TABLE IF NOT EXISTS `sms_senders` (
                    `id` INT AUTO_INCREMENT PRIMARY KEY,
                    `tenant_id` INT NULL,
                    `sender_id` VARCHAR(11) NOT NULL,
                    `status` ENUM('pending','approved','rejected') NOT NULL DEFAULT 'pending',
                    `status_source` ENUM('gateway','manual') NOT NULL DEFAULT 'gateway',
                    `sample_message` VARCHAR(160) NULL,
                    `is_default` TINYINT(1) NOT NULL DEFAULT 0,
                    `org_unit_id` INT NULL,
                    `submitted_by` INT NULL,
                    `last_checked_at` DATETIME NULL,
                    `last_check_note` VARCHAR(255) NULL,
                    `approved_at` DATETIME NULL,
                    `rejection_note` VARCHAR(255) NULL,
                    `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                    UNIQUE KEY `uniq_sms_sender_tenant` (`tenant_id`, `sender_id`),
                    INDEX `idx_sms_sender_status` (`status`),
                    FOREIGN KEY (`org_unit_id`) REFERENCES `org_units`(`id`) ON DELETE SET NULL,
                    FOREIGN KEY (`submitted_by`) REFERENCES `users`(`id`) ON DELETE SET NULL
                ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4");

                $pdo->exec("CREATE TABLE IF NOT EXISTS `sms_contacts` (
                    `id` INT AUTO_INCREMENT PRIMARY KEY,
                    `tenant_id` INT NULL,
                    `name` VARCHAR(150) NULL,
                    `msisdn` VARCHAR(20) NOT NULL COMMENT 'Normalised: dial code + national number, no plus',
                    `country_code` VARCHAR(4) NOT NULL DEFAULT '234',
                    `email` VARCHAR(190) NULL,
                    `org_unit_id` INT NULL,
                    `source` ENUM('manual','newcomer','subscriber','team','testimony','registration','form','app','import','member') NOT NULL DEFAULT 'manual',
                    `source_ref_id` INT NULL,
                    `tags` VARCHAR(255) NULL,
                    `is_opted_out` TINYINT(1) NOT NULL DEFAULT 0,
                    `opt_out_at` DATETIME NULL,
                    `notes` VARCHAR(500) NULL,
                    `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                    `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
                    UNIQUE KEY `uniq_sms_contact` (`tenant_id`, `msisdn`),
                    INDEX `idx_sms_contact_unit` (`org_unit_id`),
                    INDEX `idx_sms_contact_source` (`source`),
                    INDEX `idx_sms_contact_optout` (`is_opted_out`),
                    FOREIGN KEY (`org_unit_id`) REFERENCES `org_units`(`id`) ON DELETE SET NULL
                ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4");

                $pdo->exec("CREATE TABLE IF NOT EXISTS `sms_groups` (
                    `id` INT AUTO_INCREMENT PRIMARY KEY,
                    `tenant_id` INT NULL,
                    `name` VARCHAR(150) NOT NULL,
                    `slug` VARCHAR(170) NOT NULL,
                    `kind` ENUM('static','dynamic') NOT NULL DEFAULT 'static',
                    `rule` JSON NULL COMMENT 'Dynamic segments: the rule rows that build the audience',
                    `org_unit_id` INT NULL,
                    `created_by` INT NULL,
                    `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                    UNIQUE KEY `uniq_sms_group_slug` (`tenant_id`, `slug`),
                    FOREIGN KEY (`org_unit_id`) REFERENCES `org_units`(`id`) ON DELETE SET NULL,
                    FOREIGN KEY (`created_by`) REFERENCES `users`(`id`) ON DELETE SET NULL
                ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4");

                // PK on the pair, so adding the same contact twice is a no-op.
                $pdo->exec("CREATE TABLE IF NOT EXISTS `sms_group_members` (
                    `group_id` INT NOT NULL,
                    `contact_id` INT NOT NULL,
                    `added_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                    PRIMARY KEY (`group_id`, `contact_id`),
                    INDEX `idx_sgm_contact` (`contact_id`),
                    FOREIGN KEY (`group_id`) REFERENCES `sms_groups`(`id`) ON DELETE CASCADE,
                    FOREIGN KEY (`contact_id`) REFERENCES `sms_contacts`(`id`) ON DELETE CASCADE
                ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4");

                $pdo->exec("CREATE TABLE IF NOT EXISTS `sms_templates` (
                    `id` INT AUTO_INCREMENT PRIMARY KEY,
                    `tenant_id` INT NULL,
                    `name` VARCHAR(150) NOT NULL,
                    `body` TEXT NOT NULL,
                    `org_unit_id` INT NULL,
                    `created_by` INT NULL,
                    `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                    FOREIGN KEY (`org_unit_id`) REFERENCES `org_units`(`id`) ON DELETE SET NULL,
                    FOREIGN KEY (`created_by`) REFERENCES `users`(`id`) ON DELETE SET NULL
                ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4");

                $pdo->exec("CREATE TABLE IF NOT EXISTS `sms_campaigns` (
                    `id` INT AUTO_INCREMENT PRIMARY KEY,
                    `tenant_id` INT NULL,
                    `title` VARCHAR(200) NOT NULL,
                    `message` TEXT NOT NULL,
                    `sender_id` VARCHAR(11) NULL,
                    `group_id` INT NULL,
                    `status` ENUM('draft','scheduled','queued','sending','sent','partial','failed','cancelled') NOT NULL DEFAULT 'draft',
                    `scheduled_at` DATETIME NULL,
                    `started_at` DATETIME NULL,
                    `finished_at` DATETIME NULL,
                    `total_recipients` INT NOT NULL DEFAULT 0,
                    `sent_count` INT NOT NULL DEFAULT 0,
                    `failed_count` INT NOT NULL DEFAULT 0,
                    `skipped_count` INT NOT NULL DEFAULT 0,
                    `units_charged` INT NOT NULL DEFAULT 0,
                    `estimated_units` INT NOT NULL DEFAULT 0,
                    `created_by` INT NULL,
                    `org_unit_id` INT NULL,
                    `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                    INDEX `idx_sms_campaign_status` (`status`, `scheduled_at`),
                    FOREIGN KEY (`group_id`) REFERENCES `sms_groups`(`id`) ON DELETE SET NULL,
                    FOREIGN KEY (`created_by`) REFERENCES `users`(`id`) ON DELETE SET NULL,
                    FOREIGN KEY (`org_unit_id`) REFERENCES `org_units`(`id`) ON DELETE SET NULL
                ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4");

                // Unique on (campaign, msisdn) so a retry after a crash can never send
                // the same message to the same person twice.
                $pdo->exec("CREATE TABLE IF NOT EXISTS `sms_campaign_recipients` (
                    `id` INT AUTO_INCREMENT PRIMARY KEY,
                    `campaign_id` INT NOT NULL,
                    `contact_id` INT NULL,
                    `msisdn` VARCHAR(20) NOT NULL,
                    `name` VARCHAR(150) NULL,
                    `status` ENUM('pending','sent','failed','skipped') NOT NULL DEFAULT 'pending',
                    `units` INT NOT NULL DEFAULT 0,
                    `error_code` VARCHAR(10) NULL,
                    `error_note` VARCHAR(255) NULL,
                    `attempts` INT NOT NULL DEFAULT 0,
                    `sent_at` DATETIME NULL,
                    `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                    UNIQUE KEY `uniq_sms_recipient` (`campaign_id`, `msisdn`),
                    INDEX `idx_scr_status` (`campaign_id`, `status`),
                    FOREIGN KEY (`campaign_id`) REFERENCES `sms_campaigns`(`id`) ON DELETE CASCADE,
                    FOREIGN KEY (`contact_id`) REFERENCES `sms_contacts`(`id`) ON DELETE SET NULL
                ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4");

                // Every gateway call. The token is deliberately absent from this table.
                $pdo->exec("CREATE TABLE IF NOT EXISTS `sms_messages_log` (
                    `id` INT AUTO_INCREMENT PRIMARY KEY,
                    `tenant_id` INT NULL,
                    `campaign_id` INT NULL,
                    `endpoint` VARCHAR(40) NOT NULL,
                    `recipient_count` INT NOT NULL DEFAULT 0,
                    `recipient_sample` VARCHAR(255) NULL COMMENT 'First few numbers only, never the whole list',
                    `sender_id` VARCHAR(11) NULL,
                    `request_summary` VARCHAR(500) NULL COMMENT 'Never the token',
                    `error_code` VARCHAR(10) NULL,
                    `error_note` VARCHAR(255) NULL,
                    `http_status` INT NULL,
                    `duration_ms` INT NULL,
                    `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                    INDEX `idx_sml_created` (`created_at`),
                    INDEX `idx_sml_endpoint` (`endpoint`, `created_at`)
                ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4");

                $pdo->exec("CREATE TABLE IF NOT EXISTS `sms_wallet_log` (
                    `id` INT AUTO_INCREMENT PRIMARY KEY,
                    `tenant_id` INT NULL,
                    `balance` DECIMAL(12,2) NULL,
                    `error_code` VARCHAR(10) NULL,
                    `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                    INDEX `idx_swl_created` (`created_at`),
                    INDEX `idx_swl_tenant` (`tenant_id`, `created_at`)
                ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4");
            },
        ];
    }

    private static function addColumnIfMissing(PDO $pdo, string $table, string $column, string $definition, ?string $after): void
    {
        $check = $pdo->prepare('SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = ? AND COLUMN_NAME = ?');
        $check->execute([$table, $column]);
        if ((int) $check->fetchColumn() > 0) {
            return;
        }
        $sql = 'ALTER TABLE `' . $table . '` ADD COLUMN `' . $column . '` ' . $definition;
        if ($after) {
            $sql .= ' AFTER `' . $after . '`';
        }
        $pdo->exec($sql);
    }

    /** Adds an index (or unique key) when no index of that name already exists. */
    private static function addIndexIfMissing(PDO $pdo, string $table, string $indexName, string $definition): void
    {
        $check = $pdo->prepare('SELECT COUNT(*) FROM information_schema.STATISTICS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = ? AND INDEX_NAME = ?');
        $check->execute([$table, $indexName]);
        if ((int) $check->fetchColumn() > 0) {
            return;
        }
        $pdo->exec('ALTER TABLE `' . $table . '` ADD ' . $definition);
    }

    private static function addForeignKeyIfMissing(PDO $pdo, string $table, string $constraint, string $column, string $refTable, string $refColumn, string $onDelete): void
    {
        $check = $pdo->prepare('SELECT COUNT(*) FROM information_schema.TABLE_CONSTRAINTS WHERE CONSTRAINT_SCHEMA = DATABASE() AND TABLE_NAME = ? AND CONSTRAINT_NAME = ?');
        $check->execute([$table, $constraint]);
        if ((int) $check->fetchColumn() > 0) {
            return;
        }
        $pdo->exec("ALTER TABLE `{$table}` ADD CONSTRAINT `{$constraint}` FOREIGN KEY (`{$column}`) REFERENCES `{$refTable}`(`{$refColumn}`) ON DELETE {$onDelete}");
    }

    /** Builds a fresh PDO from arbitrary credentials without touching the singleton — used by the installer. */
    public static function testConnection(string $host, int $port, string $database, string $username, string $password): PDO
    {
        $dsn = sprintf('mysql:host=%s;port=%d;dbname=%s;charset=utf8mb4', $host, $port, $database);
        return new PDO($dsn, $username, $password, [
            PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION,
            PDO::MYSQL_ATTR_USE_BUFFERED_QUERY => true,
        ]);
    }

    /**
     * Naive but sufficient statement splitter for our own schema.sql. Splits on
     * ';' outside of string literals and backticks, so semicolons inside column
     * COMMENTS and seeded data can't break the import.
     */
    public static function importSqlFile(PDO $pdo, string $path): void
    {
        $sql = (string) file_get_contents($path);
        $sql = preg_replace('/^--.*$/m', '', $sql); // strip line comments
        foreach (self::splitStatements($sql) as $statement) {
            // query()+fetchAll() consumes any result set (e.g. an EXECUTE of a
            // SELECT) so the next statement never trips MySQL's "unbuffered
            // query active" (SQLSTATE 2014) error.
            $pdo->query($statement)->fetchAll();
        }
    }

    /** Splits SQL into statements, honouring '...' and `...` with '' / `` / \\ escapes. */
    private static function splitStatements(string $sql): array
    {
        $statements = [];
        $buffer = '';
        $length = strlen($sql);
        $quote = null;
        for ($i = 0; $i < $length; $i++) {
            $char = $sql[$i];
            if ($quote !== null) {
                $buffer .= $char;
                if ($char === $quote) {
                    // MySQL escapes a quote inside a string by doubling it ('' or ``).
                    if ($i + 1 < $length && $sql[$i + 1] === $quote) {
                        $buffer .= $sql[$i + 1];
                        $i++;
                    } else {
                        $quote = null;
                    }
                } elseif ($char === '\\' && $i + 1 < $length) {
                    $buffer .= $sql[$i + 1];
                    $i++;
                }
                continue;
            }
            if ($char === "'" || $char === '`') {
                $quote = $char;
                $buffer .= $char;
                continue;
            }
            if ($char === ';') {
                $trimmed = trim($buffer);
                if ($trimmed !== '') {
                    $statements[] = $trimmed;
                }
                $buffer = '';
                continue;
            }
            $buffer .= $char;
        }
        $trimmed = trim($buffer);
        if ($trimmed !== '') {
            $statements[] = $trimmed;
        }
        return $statements;
    }
}
