<?php
declare(strict_types=1);

/**
 * Generated by the installer on 2026-08-29 20:29:30.
 * Regenerate by deleting storage/installed.lock and re-running /install.
 */
return array (
  'driver' => 'mysql',
  'host' => 'localhost',
  'port' => 3306,
  'database' => 'yaya_sop',
  'username' => 'yaya_sop',
  'password' => 'yaya_sop',
  'charset' => 'utf8mb4',
);
