<?php
declare(strict_types=1);

/**
 * Brute-force thresholds + anonymous fingerprint salt.
 * fingerprint_salt was regenerated by the installer on 2026-08-04 16:15:02.
 */
return array (
  'max_user_failures' => 5,
  'user_protection_period' => 15,
  'max_ip_failures' => 10,
  'ip_protection_period' => 15,
  'ip_block_duration_minutes' => 60,
  'unknown_user_block_minutes' => 1440,
  'auto_whitelist_after_sessions' => 5,
  'fingerprint_salt' => '10b2274bd6e665bf2ea70c09c26297605dc7a4874393f7831ce46d081175cadf',
  'rate_limits' => 
  array (
    'feed' => 
    array (
      'limit' => 60,
      'window' => 60,
    ),
    'search' => 
    array (
      'limit' => 20,
      'window' => 60,
    ),
    'likes' => 
    array (
      'limit' => 10,
      'window' => 60,
    ),
    'views' => 
    array (
      'limit' => 30,
      'window' => 60,
    ),
    'prayer' => 
    array (
      'limit' => 5,
      'window' => 300,
    ),
    'newsletter' => 
    array (
      'limit' => 5,
      'window' => 300,
    ),
  ),
);
